### ISSUE TITLE
运行 flutter pub get 报错

### ISSUE THREAD

**Issue by byteot** [openimsdk/openim-flutter-demo#10]
Because openim_enterprise_chat depends on flutter_openim_widget from path which doesn't exist (could not find package flutter_openim_widget at "..\flutter_openim_widget"), version solving failed.

运行flutter pub get 报上边的错误

**Comment by byteot** [comment]
@hrxiang @memory-qianxiao @skiffer-git

**Comment by hrxiang** [comment]
```
flutter_openim_widget:
     git:
        url: https://github.com/hrxiang/flutter_openim_widget.git
```
