### ISSUE TITLE
flutter demo start iOS report an error

### ISSUE THREAD

**Issue by MrJiangbenba** [openimsdk/openim-flutter-demo#104]
### What happened?

<img width="1131" alt="截屏2024-03-19 17 36 04" src="https://github.com/openimsdk/open-im-flutter-demo/assets/94910232/4e4ef913-0240-4a09-a15b-97515bc102ac">

### What did you expect to happen?

<img width="1131" alt="截屏2024-03-19 17 36 04" src="https://github.com/openimsdk/open-im-flutter-demo/assets/94910232/1c7f393d-1704-4096-a255-fc12cad6c291">

### How can we reproduce it (as minimally and precisely as possible)?

 this is my Related environment configuration
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.3.1 23D60 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.5)
[✓] VS Code (version 1.87.2)
 Dart 3.3.0 •
 DevTools 2.31.1

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Compile the app using a real machine.
