### ISSUE TITLE
Bug: No known class method for selector 'registerActivityToken:'

### ISSUE THREAD

**Issue by zoujiaqing** [openimsdk/openim-flutter-demo#106]
### What happened?

```objc
- (void)registerActivityToken:(FlutterMethodCall*)call result:(FlutterResult)result {
    NSDictionary *ConfigurationInfo = call.arguments;
    [GeTuiSdk registerActivityToken:ConfigurationInfo[@"token"]];
}
```

### What did you expect to happen?

flutter run fro iOS

### How can we reproduce it (as minimally and precisely as possible)?

non

### version

master

### Cloud provider

non

### OS version

macOS 14.x

### Install tools

<details>
</details>

**Comment by std-s** [comment]
@zoujiaqing If there is a problem with the plug-in that I push, you can check their issue. You can also remove this plug-in.

**Comment by wozaihu** [comment]
确实是个坑，项目中默认的GTSDK (3.0.5.0)没有registerActivityToken，需要手动改为GTSDK (3.0.2.0)，重新pod install
