### ISSUE TITLE
Bug: Lack of language switching function

### ISSUE THREAD

**Issue by zoujiaqing** [openimsdk/openim-flutter-demo#107]
### What happened?

Lack of language switching function.

Please provide complete functional demo code, thank you.

### What did you expect to happen?

Lack of language switching function.

### How can we reproduce it (as minimally and precisely as possible)?

Lack of language switching function.

### version

Android / iOS

### Cloud provider

non

**Comment by std-s** [comment]
Please develop simple functions by yourself. This Demo mainly demonstrates some examples of using the API of IM SDK.
