### ISSUE TITLE
[BUG] [Flutter3.5.1]

### ISSUE THREAD

**Issue by Dove900412** [openimsdk/openim-flutter-demo#109]
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

I/F-OpenIMSDK(native call flutter)( 5952): method: 【 getSelfUserInfo 】, onError: { code:400, message:400 Key: 'GetUsersInfoReq.OperationID' Error:Field validation for 'OperationID' failed on the 'required' tag
I/F-OpenIMSDK(native call flutter)( 5952): Key: 'GetUsersInfoReq.UserIDList' Error:Field validation for 'UserIDList' failed on the 'required' tag}
I/flutter ( 5952): debug v  login e: PlatformException(400, 400 Key: 'GetUsersInfoReq.OperationID' Error:Field validation for 'OperationID' failed on the 'required' tag
I/flutter ( 5952): Key: 'GetUsersInfoReq.UserIDList' Error:Field validation for 'UserIDList' failed on the 'required' tag, null, null)
登录时报错

**Comment by Dove900412** [comment]
var user = await OpenIM.iMManager.login(userID: uid, token: token);

**Comment by Dove900412** [comment]
服务端 v3.6

**Comment by std-s** [comment]
Hi, 3.8 is released, please use it.
