### ISSUE TITLE
Module 'flutter_openim_sdk' not found.

### ISSUE THREAD

**Issue by johnbaoss** [openimsdk/openim-flutter-demo#111]
### OpenIM Server Version

latest

### Operating System and CPU Architecture

macOS M2 (ARM)/ Sonoma 14.5 /simulator ios 17.4/ iphone 15

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

After pulling the official Flutter demo, running flutter pub get and flutter run resulted in an error:

Failed to build iOS app
ARC Semantic Issue (Xcode): No known class method for selector 'registerActivityToken:'
/Users/eric/.pub-cache/hosted/pub.dev/getuiflut-0.2.18/ios/Classes/GetuiflutPlugin.m:222:14
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/171434934/6f7539d5-6154-49a5-b6eb-576ac57fb8b6)

Updating the  latest version of getuiflut fixed the initial bug but triggered a new one:
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found
/Users/eric/Dev/open-im/ios/Runner/GeneratedPluginRegistrant.m:89:8
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/171434934/e538a9dd-a0cb-40e0-bea3-fe472c2e31d7)

### Screenshots Link

![image](https://github.com/openimsdk/open-im-flutter-demo/assets/171434934/1b266fa2-bd24-4cbc-a1e0-f9c9a17883b0)

**Comment by johnbaoss** [comment]
After pulling the official Flutter demo, running flutter pub get and flutter run resulted in an error:

Failed to build iOS app
ARC Semantic Issue (Xcode): No known class method for selector 'registerActivityToken:'
/Users/eric/.pub-cache/hosted/pub.dev/getuiflut-0.2.18/ios/Classes/GetuiflutPlugin.m:222:14
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/171434934/6f7539d5-6154-49a5-b6eb-576ac57fb8b6)

Updating the  latest version of getuiflut fixed the initial bug but triggered a new one:
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found
/Users/eric/Dev/open-im/ios/Runner/GeneratedPluginRegistrant.m:89:8
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/171434934/e538a9dd-a0cb-40e0-bea3-fe472c2e31d7)

**Comment by xsdhbh** [comment]
兄弟解决了吗 我也遇到这个问题了

**Comment by Dreamweaver484** [comment]
一样，遇到这个问题没搞定

**Comment by std-s** [comment]
Hi, use a real machine to test, otherwise you need to configure it yourself.

**Comment by xsdhbh** [comment]
> Hi, use a real machine to test, otherwise you need to configure it yourself.

怎么配置

**Comment by std-s** [comment]
You can search for relevant documents on Google.

**Comment by std-s** [comment]
Close it first, then open it if there is a problem.

**Comment by WHChaw** [comment]
I’m facing the same issue.
