### ISSUE TITLE
[BUG] Clicking to initiate a voice call during a group chat causes the page to crash

### ISSUE THREAD

**Issue by q80671428** [openimsdk/openim-flutter-demo#114]
### OpenIM Server Version

DEMO:V3.5.1 SDK：3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

void call() {
    if (rtcIsBusy) {
      IMViews.showToast(StrRes.callingBusy);
      return;
    }

    IMViews.openIMCallSheet(nickname.value, (index) {
      imLogic.call(
        callObj: CallObj.single,
        callType: index == 0 ? CallType.audio : CallType.video,
        inviteeUserIDList: [if (isSingleChat) userID!],
      );
    });
  }
  
 When calling the call method, inviteUserIDList is empty, causing the crash at:
  Future<void> toggle(ToggleMessage msg) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[msg]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      **throw _createConnectionError(__pigeon_channelName);**
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
  
  

### Screenshots Link

![1](https://github.com/user-attachments/assets/c9db14c1-afe4-4968-ac15-e818a8b49e02)

**Comment by std-s** [comment]
Hi, the open source version only has basic single chat audio and video.
