### ISSUE TITLE
[BUG] flutter run后报错Error (Xcode): lib/core/controller/im_controller.dart:51:9: Error: No named parameter with the name 'onUserTokenInvalid'.

### ISSUE THREAD

**Issue by kinmonkey7** [openimsdk/openim-flutter-demo#118]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

jintao@jintaodeMacBook-Pro Open-IM-Flutter-Demo % flutter run
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...                                           2,197ms
Running Xcode build...                                                  
Xcode build done.                                           36.6s
Failed to build iOS app
Error (Xcode): lib/core/controller/im_controller.dart:51:9: Error: No named parameter with the name 'onUserTokenInvalid'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

**Comment by std-s** [comment]
Is your client SDK correct?

**Comment by kinmonkey7** [comment]
> 你的客户端SDK正确吗？

安装的最新的[SDK-3.8.1-rc.0](https://github.com/openimsdk/open-im-flutter-demo/releases/tag/SDK-3.8.1-rc.0)，但是pub.dev中的最新版本是flutter_openim_sdk 3.8.0
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/24a2155c-2502-4345-a174-172fa478b43b">，是否冲突

**Comment by std-s** [comment]
Use [the method](https://github.com/openimsdk/open-im-flutter-demo/blob/6edb93e99188e2c5c153eb9d4b286e42b3bd5d77/pubspec.yaml#L114-L117) in Demo to introduce it. Pub will be updated later.

**Comment by std-s** [comment]
The SDK in the demo is already configured, so do not change it.
