### ISSUE TITLE
最新的demo似乎运行不起来

### ISSUE THREAD

**Issue by lnd1992** [openimsdk/openim-flutter-demo#12]
![截屏2022-01-08 下午4 15 03](https://user-images.githubusercontent.com/24648203/148637218-2275f041-73eb-4e5d-9661-0dd1b3e0d9d3.png)

**Comment by hrxiang** [comment]
> ![截屏2022-01-08 下午4 15 03](https://user-images.githubusercontent.com/24648203/148637218-2275f041-73eb-4e5d-9661-0dd1b3e0d9d3.png)

嗯，已修复
