### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zisequkuai** [openimsdk/openim-flutter-demo#120]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running pod install...                                              9.8s
Running Xcode build...                                                 ⣷
 
 └─Compiling, linking and signing...                         4.9s
Xcode build done.                                           78.2s
Failed to build iOS app
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found
/open-im-flutter-demo-main/ios/Runner/GeneratedPluginRegistrant.m:89:8

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**openim 官方文档中已经描述了 更换IM SDK版本
// openim_common/pubspec.yaml
// openim_live/pubspec.yaml
// pubspec.yaml

 要替换  flutter_openim_sdk: lastest ，**

我已经修改了
 openim_common/pubspec.yaml
 openim_live/pubspec.yaml
 pubspec.yaml 三个文件中的

flutter_openim_sdk: 
    path:  /open-im-sdk-flutter-main 

但是还是出错 Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

请问是什么原因

**Comment by std-s** [comment]
Use a real device.

**Comment by zisequkuai** [comment]
谢谢。@std-s 确实解决了。但是为什么不能在模拟器里成功呢？ 问题在哪里

**Comment by std-s** [comment]
Please refer to the relevant information to configure the iOS project yourself.
