### ISSUE TITLE
[BUG] This demo can't run at all, all kinds of errors are reported, it's so annoying

### ISSUE THREAD

**Issue by chenyu1990** [openimsdk/openim-flutter-demo#123]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

能不能好好搞个demo啊，环境的各版本号弄清楚啊
按文档的用 flutter 3.22.3
android sdk 35.1
跑不起来

**Comment by chenyu1990** [comment]
什么玩意儿，浪费我几个小时，c

**Comment by chenyu1990** [comment]
到底要搭配什么jdk版本，什么gradle版本，什么ndk版本，才能跑起来了？换了几个小时了，一直报各种错，焦麻了！

**Comment by EdenYK** [comment]
哈哈哈哈

**Comment by chenyu1990** [comment]
> 哈哈哈哈

😕

**Comment by std-s** [comment]
You can ask Android colleagues to help you.

**Comment by std-s** [comment]
I close it first and then open it again if there is a problem.
