### ISSUE TITLE
[BUG]iOS can't run at all, and reports an error Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead

### ISSUE THREAD

**Issue by weiwuxing** [openimsdk/openim-flutter-demo#124]
### OpenIM Server Version

最新版

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

运行demo的时候，对应pod都已经成功了。启动运行时报错，无法启动。Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead，可以把demo调好吗

### Screenshots Link

运行demo的时候，对应pod都已经成功了。启动运行时报错，无法启动。Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead，可以把demo调好吗

**Comment by std-s** [comment]
Could you please ask your iOS engineers how to solve it?

**Comment by std-s** [comment]
I close it first and then open it again if there is a problem.
