### ISSUE TITLE
[FEATURE REQUEST]  The Flutter source code seems to have some functional differences from the current Android/iOS versions

### ISSUE THREAD

**Issue by rgmyyw** [openimsdk/openim-flutter-demo#125]
### Why this feature?

比如阅后即焚,表情, 已读之类的, 另外就是 正在输入 貌似现在是直接 throw了,  该示例是否任然在开发? 

### Suggested Solution

期望能和现有iOS/Android 功能一致

**Comment by std-s** [comment]
@rgmyyw The open source demo only shows the use of the SDK, and you can develop it yourself.

**Comment by std-s** [comment]
I close it first and then open it again if there is a problem.
