### ISSUE TITLE
[Other]: Assistance with Running OpenIM SDK in Background Mode for Local Notifications

### ISSUE THREAD

**Issue by buiphukhuyen** [openimsdk/openim-flutter-demo#126]
### What would you like to share?

Hello,

I’m currently working on a project that utilizes OpenIM SDK, and I’m facing an issue with running the SDK in background mode to push local notifications. Specifically, I would like to use the onRecvNewMessage, onRecvOfflineNewMessage, and other listeners to trigger local notifications. However, the SDK seems to stop working once the app is closed, and I can’t seem to reinitialize it to run the listeners in the background.

I have integrated the SDK with flutter_background_service to maintain the service in the background, but OpenIM does not reconnect or trigger any listeners unless the app is reopened. Could you please provide guidance on how to set up OpenIM SDK to work persistently in the background? Is there a recommended way to ensure that these listeners continue to function even after the app is closed?

Thank you very much for your assistance!

Best regards,

**Comment by std-s** [comment]
When the app switches to the background, please use offline push.
