### ISSUE TITLE
sdk typingStatusUpdate Deprecated

### ISSUE THREAD

**Issue by whevether** [openimsdk/openim-flutter-demo#128]
### Why this feature?

sdk typingStatusUpdate @Deprecated('Use [OpenIM.iMManager.conversationManager.changeInputStates(conversationID:focus:)] instead') 

### Suggested Solution

Please update the code

**Comment by std-s** [comment]
The [code](https://github.com/openimsdk/open-im-sdk-flutter/blob/91b0f4eb001b88b1c5dee0b0bc57b79dccd588bd/lib/src/manager/im_conversation_manager.dart#L350) exist.

**Comment by whevether** [comment]
> The [code](https://github.com/openimsdk/open-im-sdk-flutter/blob/91b0f4eb001b88b1c5dee0b0bc57b79dccd588bd/lib/src/manager/im_conversation_manager.dart#L350) exist.

SDK does exist. What I want to know is how to use the demo

**Comment by std-s** [comment]
@whevether  https://docs.openim.io/sdks/api/conversation/changeInputStates

**Comment by std-s** [comment]
It has not responded for a long time, close it first.
