### ISSUE TITLE
[BUG] The handling of token expiration and invalidation is too rough

### ISSUE THREAD

**Issue by DreamerIG** [openimsdk/openim-flutter-demo#129]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

当我在使用app时，在整个APP运行过程当中都应该监听用户Token状态，如果服务器重启，用户token又没有刷新，就会报错，

**Comment by std-s** [comment]
hi, this is just an open source Demo. Its main function is to introduce how to use the SDK. Detailed business logic can be added by yourself.
