### ISSUE TITLE
iOS 模拟器运行 Unable to find a destination matching the provided destination specifier

### ISSUE THREAD

**Issue by RogueYBJ** [openimsdk/openim-flutter-demo#15]
![image](https://user-images.githubusercontent.com/30822939/149861482-42572f5d-bfe5-4a27-9738-b7bb5118362e.png)

**Comment by hrxiang** [comment]
![WeChat0cfbf3f891c42c9ad7ed740939129fb6](https://user-images.githubusercontent.com/7018230/149866465-5ceab62e-bc8f-4bd4-8c66-5bd00b11a0d0.png)

**Comment by hrxiang** [comment]
运行指定设备id

**Comment by brant9527** [comment]
哪个文件可以跟rn一样配置指定设备，目前已经设置过相应设备为boot，但是启动还是提示找不到设备

**Comment by hrxiang** [comment]
ios最低要求11，你先检查一下ios版本

**Comment by brant9527** [comment]
ios 版本是 13.0 和15.2的

**Comment by hrxiang** [comment]
开了几个模拟器？

**Comment by brant9527** [comment]
开两个和一个，到最后都是会报同样的错误

**Comment by shareCourage** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/10915651/154728528-931b1362-a4e1-4f6b-9eea-e42570550d7c.png">
看下这个配置，可能不支持模拟器
