### ISSUE TITLE
Android编译报错

### ISSUE THREAD

**Issue by hxnets** [openimsdk/openim-flutter-demo#16]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\flutter\.pub-cache\hosted\pub.flutter-io.cn\better_player-0.0.81\android\build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':better_player'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':better_player'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleRelease'...                           12.9s
Gradle task assembleRelease failed with exit code 1

build.gradle增加了kotlin-android包也不行

**Comment by hrxiang** [comment]
![WeChatffe67f57f6f083e86ac9768c9fe80db6](https://user-images.githubusercontent.com/7018230/150707670-87a3e31f-4a4b-46d0-a7c0-28a4f59ae1de.png)

**Comment by hxnets** [comment]
> ![WeChatffe67f57f6f083e86ac9768c9fe80db6](https://user-images.githubusercontent.com/7018230/150707670-87a3e31f-4a4b-46d0-a7c0-28a4f59ae1de.png)

我昨晚用1.5测试的 没成功，今晚改成1.6试试

**Comment by hrxiang** [comment]
```
buildscript {
    ext.kotlin_version="1.6.10"
    repositories {
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/gradle-plugin' }
        maven { url 'https://developer.huawei.com/repo/' }    // hms
        maven { url "https://dl.google.com/dl/android/maven2/" }   // fcm
//        maven { url "https://maven.google.com" }   // fcm
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.5'  // fcm
        classpath 'com.huawei.agconnect:agcp:1.4.2.300'    // hms
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }
        maven { url 'https://maven.aliyun.com/nexus/content/repositories/gradle-plugin' }
        maven { url 'https://developer.huawei.com/repo/' }    // hms
        maven { url "https://dl.google.com/dl/android/maven2/" }   // fcm
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by hxnets** [comment]
> ```
> buildscript {
>     ext.kotlin_version="1.6.10"
>     repositories {
>         maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/gradle-plugin' }
>         maven { url 'https://developer.huawei.com/repo/' }    // hms
>         maven { url "https://dl.google.com/dl/android/maven2/" }   // fcm
> //        maven { url "https://maven.google.com" }   // fcm
>         google()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:4.1.3'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>         classpath 'com.google.gms:google-services:4.3.5'  // fcm
>         classpath 'com.huawei.agconnect:agcp:1.4.2.300'    // hms
>     }
> }
> 
> allprojects {
>     repositories {
>         maven { url 'https://maven.aliyun.com/nexus/content/groups/public/' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/jcenter' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/google' }
>         maven { url 'https://maven.aliyun.com/nexus/content/repositories/gradle-plugin' }
>         maven { url 'https://developer.huawei.com/repo/' }    // hms
>         maven { url "https://dl.google.com/dl/android/maven2/" }   // fcm
>         google()
>         mavenCentral()
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> ```

谢谢哥，编译成功了。
