### ISSUE TITLE
android12无法安装，显示无法解析安装包

### ISSUE THREAD

**Issue by lucasjinreal** [openimsdk/openim-flutter-demo#17]
android12无法安装，显示无法解析安装包

**Comment by hrxiang** [comment]
> android12无法安装，显示无法解析安装包

下载的安装包有多大，我们的安装包应该有48m的样子，12的真机手里没得，用的模拟器，模拟器没问题。

**Comment by lucasjinreal** [comment]
47m，显示无法解析安装包，flutter是否升级到了2.10？否则无法支持android12， 可以升级编译一波，性能提升了很多

**Comment by hrxiang** [comment]
> 47m，显示无法解析安装包，flutter是否升级到了2.10？否则无法支持android12， 可以升级编译一波，性能提升了很多

目前在重构sdk，需要等sdk更新后才能更新demo。新版本sdk很快就要发布了再等等。

**Comment by lucasjinreal** [comment]
@hrxiang 好的，非常期待。大概沙时候sdk可以更新亚

**Comment by hrxiang** [comment]
> @hrxiang 好的，非常期待。大概沙时候sdk可以更新亚

还在调试，好像定的是2.14一起更新服务端跟移动端sdk，有可能提前。

**Comment by lucasjinreal** [comment]
@hrxiang 可以更新到最新的sdk了吗
