### ISSUE TITLE
Cannot create link

### ISSUE THREAD

**Issue by szxv587** [openimsdk/openim-flutter-demo#2]
Cannot create link, path = 'D:\flutter\.pub-cache\_temp\dir92afd9ae\ios\Classes\AudioPlayer.m' (OS Error: 客户端没有所需的特权。
, errno = 1314)
pub get failed (66; , errno = 1314))

**Comment by MMMMMLiang** [comment]
> Cannot create link, path = 'D:\flutter.pub-cache_temp\dir92afd9ae\ios\Classes\AudioPlayer.m' (OS Error: 客户端没有所需的特权。 , errno = 1314) pub get failed (66; , errno = 1314))

AS右键以管理员身份运行
