### ISSUE TITLE
模拟器调试报错    xcodebuild: error: Unable to find a destination matching the provided destination specifier:

### ISSUE THREAD

**Issue by meichengkeji** [openimsdk/openim-flutter-demo#20]
Launching lib/main.dart on iPhone Xs in debug mode...
Running Xcode build...
Xcode build done.                                            2.4s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-02-12 06:01:36.470 xcodebuild[7986:1194496]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-18108/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 00008020-00151DD63483002E was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fd6e79aaea0>
    Method:   -platform
    Thread:   <NSThread: 0x7fd6e6c968d0>{number = 3, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    xcodebuild: error: Unable to find a destination matching the provided destination specifier:
    		{ id:FB10AF62-7320-4F52-8992-07B32E43C03F }

    	Ineligible destinations for the "Runner" scheme:
    		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }

Could not build the application for the simulator.
Error launching application on iPhone Xs.

**Comment by brant9527** [comment]
解决了么啊

**Comment by meichengkeji** [comment]
没有 用dart重写 不用提供的sdk   ios下问题严重,还有引用的库部分也不兼容
