### ISSUE TITLE
flutter2.10.1 dart2.16.1编译报错

### ISSUE THREAD

**Issue by shareCourage** [openimsdk/openim-flutter-demo#22]
`../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1179:9: Error: Type 'TextEditingActionTarget' not found.
        TextEditingActionTarget,
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1174:7: Error: The type 'TextEditingActionTarget' can't be mixed in.
class ExtendedEditableTextState extends State<ExtendedEditableText>
      ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2598:11: Error: Superclass has no method named 'copySelection'.
    super.copySelection(cause);
          ^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2628:11: Error: Superclass has no method named 'cutSelection'.
    super.cutSelection(cause);
          ^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2638:11: Error: Superclass has no method named 'pasteText'.
    super.pasteText(cause);
          ^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2648:11: Error: Superclass has no method named 'selectAll'.
    super.selectAll(cause);
          ^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2693:11: Error: Superclass has no method named 'setSelection'.
    super.setSelection(nextSelection, cause);
          ^^^^^^^^^^^^
Failed to package /Users/PaulPan/Downloads/Code/flutter_code/Open-IM-Flutter-Demo.
`

我已经把flutter升级到最新的稳定版了，为啥还有这个错误啊

**Comment by hrxiang** [comment]
flutter pub upgrade

**Comment by wujianqiangwjq** [comment]
我也是这个问题，编译不过，这个是什么问题，我用1.0.3版本, flutter 2.10.1 dart:2.16.1

**Comment by hrxiang** [comment]
flutter_openim_widget改成git依赖试试
