### ISSUE TITLE
请跟新一下flutter android apk

### ISSUE THREAD

**Issue by lucasjinreal** [openimsdk/openim-flutter-demo#23]
还是android12无法解析安装包。。。。。

**Comment by hrxiang** [comment]
> 还是android12无法解析安装包。。。。。

能贴出控制台错误日志吗

**Comment by hrxiang** [comment]
> > 还是android12无法解析安装包。。。。。
> 
> 能贴出控制台错误日志吗

运行debug包，安装失败的时候，控制台会有错误日志

**Comment by lucasjinreal** [comment]
@hrxiang 我直接扫码下载的，无法解析，机器是android12

**Comment by hrxiang** [comment]
> @hrxiang 我直接扫码下载的，无法解析，机器是android12

源码构建然后看日志

**Comment by hrxiang** [comment]
> > @hrxiang 我直接扫码下载的，无法解析，机器是android12
> 
> 源码构建然后看日志

你想运行在12上，将极光去掉在编译

**Comment by lucasjinreal** [comment]
@hrxiang 我没有自己编译啊，为什么你们做一个demo都不支持下android12呢？这很蛋疼啊

**Comment by hrxiang** [comment]
> @hrxiang 我没有自己编译啊，为什么你们做一个demo都不支持下android12呢？这很蛋疼啊

使用了第三方插件如极光。都给你说了你可以去掉，demo 只供参考，保证im的sdk没问题就行，你的意思咋的还得完全满足你们项目？需要我帮你们把项目给写了吗？

**Comment by hrxiang** [comment]
> @hrxiang 我没有自己编译啊，为什么你们做一个demo都不支持下android12呢？这很蛋疼啊

1，自己去掉极光相关的
2，等极光更新替换最新插件

**Comment by lucasjinreal** [comment]
@hrxiang 极光不能android12吗？去掉极光那改的东西有点多啊，是否有必要？就感觉很不科学

**Comment by hrxiang** [comment]
> @hrxiang 极光不能android12吗？去掉极光那改的东西有点多啊，是否有必要？就感觉很不科学

跟极光的耦合度极地，2,3分钟就可以搞定的事，已经有人做了。不科学那你就等极光更新插件，或者你用我们插件自己开发不使用我们demo，自己选择依赖库。

**Comment by hrxiang** [comment]
提供了im sdk插件的，你直接用这个https://github.com/OpenIMSDK/Open-IM-SDK-Flutter，这个跟Android版本没关系。

**Comment by hrxiang** [comment]
build.gradle文件里的target 版本改成30试试

**Comment by lucasjinreal** [comment]
@hrxiang 可以了，你们可以更新下apk吗，以防人家其他android12项测试测试不了

**Comment by hrxiang** [comment]
> @hrxiang 可以了，你们可以更新下apk吗，以防人家其他android12项测试测试不了

更新了，你试试。
