### ISSUE TITLE
Open-IM-Flutter-Demo 工程成功打包后，发送语音和图片，客户端闪退。

### ISSUE THREAD

**Issue by whoyuhui** [openimsdk/openim-flutter-demo#24]

**Comment by hrxiang** [comment]
flutter_openim_widget 升级到最新试试

**Comment by whoyuhui** [comment]
flutter_openim_widget 0.0.6 , flutter_openim_sdk 2.0.0，发送语音时，闪退，报错

DioError ║ Status: 404 Not Found
I/flutter (26914): ║  http://121.37.25.71:10000/user/get_users_online_status


更新flutter_openim_widget后：
flutter_openim_widget 0.0.7 , flutter_openim_sdk 2.0.0+1 ，代码编译不通过，api参数不一致

**Comment by hrxiang** [comment]
> flutter_openim_widget 0.0.6 , flutter_openim_sdk 2.0.0，发送语音时，闪退，报错
> 
> DioError ║ Status: 404 Not Found I/flutter (26914): ║ http://121.37.25.71:10000/user/get_users_online_status
> 
> 更新flutter_openim_widget后： flutter_openim_widget 0.0.7 , flutter_openim_sdk 2.0.0+1 ，代码编译不通过，api参数不一致

404这个替换url为http://121.37.25.71:10000/manager/get_users_online_status
不一致就根据sdk需要什么参数传什么参数。

**Comment by hrxiang** [comment]
更新代码
