### ISSUE TITLE
模拟器运行报错 - Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by zhuzhu322** [openimsdk/openim-flutter-demo#35]
../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:28:40: Warning: Operand of null-aware operation '!' has type 'ImageCache' which excludes null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../../flutter/packages/flutter/lib/src/painting/image_cache.dart').
      return PaintingBinding.instance!.imageCache!;
                                       ^
../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.1.2/lib/src/extended_image_provider.dart:97:39: Warning: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
      () => load(key, PaintingBinding.instance!.instantiateImageCodec),
                                      ^
../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.1.2/lib/src/platform.dart:26:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
    PaintingBinding.instance?.imageCache?.clear();
                    ^
../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.1.2/lib/src/platform.dart:27:21: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
    PaintingBinding.instance?.imageCache?.clearLiveImages();
                    ^
../../.pub-cache/hosted/pub.flutter-io.cn/extended_image_library-3.1.2/lib/src/platform.dart:40:28: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('../../flutter/packages/flutter/lib/src/painting/binding.dart').
    return PaintingBinding.instance?.imageCache;
                           ^
../../.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:439:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:486:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/positioned_list.dart:312:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_widget_from_html_core-0.8.5+1/lib/src/widgets/html_table.dart:592:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance
                         ^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_widget_from_html_core-0.8.5+1/lib/src/widgets/html_table.dart:606:28: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
            WidgetsBinding.instance
                           ^
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_widget_from_html_core-0.8.5+1/lib/src/internal/ops/anchor.dart:120:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback(
                   ^
Failed to package /Users/fred/project/Open-IM-Flutter-Demo.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by hrxiang** [comment]
更新
