### ISSUE TITLE
在此基础上二次开发衍生出来的产品可以免费进行商用吗

### ISSUE THREAD

**Issue by huawenjie11** [openimsdk/openim-flutter-demo#38]
请问一下可以直接在这个flutter-demo上进行二次开发，然后衍生出来的产品可以免费进行商用吗，因为在OpenIm文档中没有看到此类对flutter-demo的说明

**Comment by hrxiang** [comment]
可以免费使用，必须在app启动页加上 (由OpenIM提供技术支持)
