### ISSUE TITLE
获取最新代码，跑步起来。flutter_openim_sdk 私库地址无法访问

### ISSUE THREAD

**Issue by guipie** [openimsdk/openim-flutter-demo#42]
flutter_openim_sdk 私库地址无法访问。

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.openim:core-sdk:2.0.9.6.
     Required by:
         project :app > project :flutter_openim_sdk
      > Could not resolve io.openim:core-sdk:2.0.9.6.
         > Could not get resource 'http://121.37.25.71:8081/repository/maven2/io/openim/core-sdk/2.0.9.6/core-sdk-2.0.9.6.pom'.
            > Could not GET 'http://121.37.25.71:8081/repository/maven2/io/openim/core-sdk/2.0.9.6/core-sdk-2.0.9.6.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
Running Gradle task 'assembleDebug'...                            106.2s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Running Gradle task 'assembleDebug'...                                 /
![image](https://user-images.githubusercontent.com/55727172/171985499-b0f9e754-77bc-4fba-b7e5-b7ea6d5f5981.png)
****

**Comment by liuywangw** [comment]
这个问题你解决了吗
