### ISSUE TITLE
flutter sdk可以支持desktop的桌面端吗？

### ISSUE THREAD

**Issue by GarrettLi77** [openimsdk/openim-flutter-demo#43]

**Comment by hrxiang** [comment]
目前没有会桌面端的，你会吗可以加入进来一起开发。

**Comment by GarrettLi77** [comment]
谢谢回复。哈哈哈我也不会桌面端😂



| |
李传琪
|
|
18769984044
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月07日 18:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [OpenIMSDK/Open-IM-Flutter-Demo] flutter sdk可以支持desktop的桌面端吗？ (Issue #43) |

目前没有会桌面端的，你会吗可以加入进来一起开发。

**Comment by hrxiang** [comment]
快了

**Comment by lucasjinreal** [comment]
@hrxiang 请问一下啥时候能支持桌面端啊，很期待

**Comment by std-s** [comment]
@lucasjinreal 会尽快支持。
