### ISSUE TITLE
最新的demo（flutter_openim_widget: ^2.0.9+1）运行ios报错！

### ISSUE THREAD

**Issue by GarrettLi77** [openimsdk/openim-flutter-demo#45]
Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Swift Compiler Error (Xcode): Cannot find 'Open_im_sdkSetGroupMemberRoleLevel' in scope
/flutter_openim_sdk-2.0.9+2/ios/Classes/Module/GroupManager.swift:120:8

**Comment by hrxiang** [comment]
升级
