### ISSUE TITLE
Starting a Gradle Daemon (subsequent builds will be faster)

### ISSUE THREAD

**Issue by floki2020** [openimsdk/openim-flutter-demo#47]
[+1804 ms] Starting a Gradle Daemon (subsequent builds will be faster)

[+20891 ms] > Configure project :app_installer

[        ] WARNING: The option setting 'android.enableR8=true' is deprecated.

[        ] It will be removed in version 5.0 of the Android Gradle plugin.

[        ] You will no longer be able to disable R8

使用的是最新版本的demo
flutter 版本 3.0.1
科学上网也试过
也用其它人的电脑调试也是这个问题
sdk的maven 也修改过都是无效的
自己新建的demo可以通过
真机测试

**Comment by hrxiang** [comment]
1，cd android
2，./gradlew clean build
