### ISSUE TITLE
下面这个一直打印的在哪里可以关闭吗，本地调试的时候一直打印有点影响

### ISSUE THREAD

**Issue by guipie** [openimsdk/openim-flutter-demo#48]
### 关闭心跳检测
![image](https://user-images.githubusercontent.com/55727172/177088067-1c44e217-fd13-463d-aba2-54316505cc69.png)

**Comment by hrxiang** [comment]
日志等级填1

**Comment by guipie** [comment]
thanks

**Comment by guipie** [comment]
设置后，还是一直在打印，flutter 客户端。
![image](https://user-images.githubusercontent.com/55727172/177106984-fcf0ef44-40e7-4128-9015-a727bbf21a28.png)

**Comment by hrxiang** [comment]
你在app来提bug ，我肯定告诉你app怎么设置。这个是在app端初始化sdk的时候填写的

**Comment by guipie** [comment]
好的
