### ISSUE TITLE
用这里代码跑起来的demo为什么和下载的demo不一样，功能差很多，是要付费吗

### ISSUE THREAD

**Issue by TabbyCute** [openimsdk/openim-flutter-demo#52]

**Comment by hrxiang** [comment]
SDK提供了所有api的，可以自己使用sdk开发。
官网开源demo至少包含了80%的功能。
完整的demo只有商业版，需要付费。

**Comment by TabbyCute** [comment]
> 

感谢！

**Comment by 0x1af2aec8f957** [comment]
@hrxiang 为什么我下载的demo跑不起来呢？只有Master和部分Tag，我都试了一下，这里面flutter的widget有很多参数的传递与定义不符，导致构建失败。还是说还需要其它什么操作才能运行呢？

比如：
![image](https://user-images.githubusercontent.com/25100196/230304199-45e1b797-f0d4-4281-8c43-3515681961d2.png)
![image](https://user-images.githubusercontent.com/25100196/230304013-741787ec-8a82-4903-87f9-2310e3130767.png)

还有一些依赖包的版本约束问题。

**Comment by std-s** [comment]
> @hrxiang 为什么我下载的demo跑不起来呢？只有Master和部分Tag，我都试了一下，这里面flutter的widget有很多参数的传递与定义不符，导致构建失败。还是说还需要其它什么操作才能运行呢？
> 
> 比如： ![image](https://user-images.githubusercontent.com/25100196/230304199-45e1b797-f0d4-4281-8c43-3515681961d2.png) ![image](https://user-images.githubusercontent.com/25100196/230304013-741787ec-8a82-4903-87f9-2310e3130767.png)
> 
> 还有一些依赖包的版本约束问题。

@0x1af2aec8f957 重新克隆代码，体验。
