### ISSUE TITLE
 android安装包不能在  android studio 模拟器运行问题

### ISSUE THREAD

**Issue by huangdevops** [openimsdk/openim-flutter-demo#53]
嗨! 请问下 根据提示 [README.md](https://github.com/OpenIMSDK/Open-IM-Flutter-Demo#readme) 提示
![image](https://user-images.githubusercontent.com/109576438/180643872-b65f25a8-afaa-4254-921f-7f75bc7b841e.png)
添加后 编译时报
![image](https://user-images.githubusercontent.com/109576438/180643895-b5308c47-13a2-4e8e-92dc-d3ba2ed38d94.png)
是添加不对?
![image](https://user-images.githubusercontent.com/109576438/180643924-cc6a727b-9812-4559-88ad-4958788ffda3.png)

**Comment by huangdevops** [comment]
![image](https://user-images.githubusercontent.com/109576438/180644362-c4dbd861-205e-4b20-910c-274bd828bc38.png)
这样 也会报错

**Comment by hrxiang** [comment]
看看是不是gradle版本问题
