### ISSUE TITLE
发送图片 上传图片出现如下错误，请问如何使其正常工作

### ISSUE THREAD

**Issue by zhengzaihong** [openimsdk/openim-flutter-demo#54]
Code: AuthFailure.SecretIdNotFound, Message: The SecretId is not found, please ensure that your SecretId is correct., RequestId: 3469099a-8ec2-417c-8d64-2fa28a3c7437]c7f52936b145506ededa591ddbcdaa84 , null, null)

**Comment by hrxiang** [comment]
服务端配置问题
