### ISSUE TITLE
A problem occurred evaluating project ':record'.

### ISSUE THREAD

**Issue by okiypx** [openimsdk/openim-flutter-demo#56]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\setup\flutter\.pub-cache\hosted\pub.dartlang.org\record-4.3.3\android\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':record'.
> No signature of method: build_u7up5pkr5fmspcw65fop6wuu.android() is applicable for argument types: (build_u7up5pkr5fmspcw65fop6wuu$_run_closure2) values: [build_u7up5pkr5fmspcw65fop6wuu$_run_closure2@e98c1bb]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
![image](https://user-images.githubusercontent.com/84972378/184464275-f2dfb4f5-caac-4429-a68d-6190d03039f3.png)

**Comment by std-s** [comment]
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Build file 'D:\setup\flutter.pub-cache\hosted\pub.dartlang.org\record-4.3.3\android\build.gradle' line: 25
> * What went wrong:
>   A problem occurred evaluating project ':record'.
> 
> > No signature of method: build_u7up5pkr5fmspcw65fop6wuu.android() is applicable for argument types: (build_u7up5pkr5fmspcw65fop6wuu$_run_closure2) values: [build_u7up5pkr5fmspcw65fop6wuu$_run_closure2@e98c1bb]
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>   ![image](https://user-images.githubusercontent.com/84972378/184464275-f2dfb4f5-caac-4429-a68d-6190d03039f3.png)

dependency_overrides:
  record: 4.1.1
