### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by okiypx** [openimsdk/openim-flutter-demo#57]
Warning: You are using these overridden dependencies:
! camera_android 0.9.7+1 (0.10.0+1 available)
! camera_avfoundation 0.9.7+1 (0.9.8+3 available)
! pull_to_refresh 2.0.0 from git https://github.com/miquelbeltran/flutter_pulltorefresh at 6d7fbd
! scrollable_positioned_list 0.3.2
! xml 6.1.0
Running "flutter pub get" in 8kp5_im_fe...                          3.8s
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
lib/src/pages/chat/chat_view.dart:148:51: Error: Required named parameter 'textEditingController' must be provided.
                          emojiView: ChatEmojiView(
                                                  ^
/D:/setup/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_openim_widget-2.3.0/lib/src/chat_emoji_view.dart:30:9: Context: Found this candidate, but the arguments don't match.
  const ChatEmojiView({
        ^^^^^^^^^^^^^
lib/src/widgets/bottombar.dart:78:21: Error: No named parameter with the name 'steam'.
                    steam: item.steam,
                    ^^^^^
/D:/setup/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_openim_widget-2.3.0/lib/src/unread_count_view.dart:5:9: Context: Found this candidate, but the arguments don't match.
  const UnreadCountView({
        ^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\setup\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\setup\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Running Gradle task 'assembleDebug'...                             25.4s
Exception: Gradle task assembleDebug failed with exit code 1
![image](https://user-images.githubusercontent.com/84972378/184470185-395f5124-b795-47a0-a7e8-5437e37b0112.png)

**Comment by std-s** [comment]
@okiypx  更新下代码。这个 widget 使用 flutter_openim_widget: 2.1.0
