### ISSUE TITLE
E/FlutterLoader( 4127): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by okiypx** [openimsdk/openim-flutter-demo#58]
E/FlutterLoader( 4127): Flutter initialization failed.
E/FlutterLoader( 4127): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 4127):         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader( 4127):         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:236)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader( 4127):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:266)
E/FlutterLoader( 4127):         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:175)
E/FlutterLoader( 4127):         at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader( 4127):         at android.app.Activity.performCreate(Activity.java:7994)
E/FlutterLoader( 4127):         at android.app.Activity.performCreate(Activity.java:7978)
E/FlutterLoader( 4127):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/FlutterLoader( 4127):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/FlutterLoader( 4127):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/FlutterLoader( 4127):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/FlutterLoader( 4127):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FlutterLoader( 4127):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FlutterLoader( 4127):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/FlutterLoader( 4127):         at android.os.Handler.dispatchMessage(Handler.java:106)
E/FlutterLoader( 4127):         at android.os.Looper.loop(Looper.java:223)
E/FlutterLoader( 4127):         at android.app.ActivityThread.main(ActivityThread.java:7656)
E/FlutterLoader( 4127):         at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 4127):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/FlutterLoader( 4127):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/FlutterLoader( 4127): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 4127):         at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/FlutterLoader( 4127):         at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/FlutterLoader( 4127):         at java.lang.System.loadLibrary(System.java:1664)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:186)
E/FlutterLoader( 4127):         at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:179)
E/FlutterLoader( 4127):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader( 4127):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader( 4127):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader( 4127):         at java.lang.Thread.run(Thread.java:923)
![image](https://user-images.githubusercontent.com/84972378/184496062-d690bd6c-31d1-466b-8fd2-f4ed67803cec.png)

**Comment by std-s** [comment]
先确认flutter环境是否安装正确。
