### ISSUE TITLE
ios 都要一年还不能跑?

### ISSUE THREAD

**Issue by simanlx** [openimsdk/openim-flutter-demo#59]
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/0j/vs2dth5157q6r3s5lcf9wfn00000gn/T/flutter_tools.k17Gnr/flutter_ios_build_temp_dirQJKD4A/temporary_xcresult_bundle

    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler_apple-9.0.4/ios/Classes/strategies/PhonePermissionStrategy.m:50:35: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
        CTCarrier *carrier = [netInfo subscriberCellularProvider];
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                      serviceSubscriberCellularProviders
    In module 'CoreTelephony' imported from /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler_apple-9.0.4/ios/Classes/strategies/PhonePermissionStrategy.m:8:
    
    - (void)assetForURL:(NSURL *)assetURL resultBlock:(ALAssetsLibraryAssetForURLResultBlock)resultBlock failureBlock:(ALAssetsLibraryAccessFailureBlock)failureBlock AL_DEPRECATED(4, "Use fetchAssetsWithLocalIdentifiers:options: on PHAsset to fetch assets by local identifier (or to lookup PHAssets by a previously known ALAssetPropertyAssetURL use fetchAssetsWithALAssetURLs:options:) from the Photos framework instead");
    ^
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:165:5: warning: 'ALAssetRepresentation' is deprecated: first deprecated in iOS 9 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead [-Wdeprecated-declarations]
        ALAssetRepresentation *representation = [assetAtUrl defaultRepresentation];
        ^
    In module 'AssetsLibrary' imported from /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:14:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:20:12: note: 'ALAssetRepresentation' has been explicitly marked deprecated here
    @interface ALAssetRepresentation : NSObject {
               ^
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:165:57: warning: 'defaultRepresentation' is deprecated: first deprecated in iOS 9 - Use PHImageRequestOptions with the PHImageManager from the Photos framework instead [-Wdeprecated-declarations]
        ALAssetRepresentation *representation = [assetAtUrl defaultRepresentation];
                                                            ^
    In module 'AssetsLibrary' imported from /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:14:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAsset.h:49:1: note: 'defaultRepresentation' has been explicitly marked deprecated here
    - (ALAssetRepresentation *)defaultRepresentation AL_DEPRECATED(4, "Use PHImageRequestOptions with the PHImageManager from the Photos framework instead");
    ^
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:166:28: warning: 'metadata' is deprecated: first deprecated in iOS 9 - Use CGImageSourceCopyPropertiesAtIndex() to retrieve metadata from an image returned by the PHImageManager from the Photos framework instead [-Wdeprecated-declarations]
        return [representation metadata];
                               ^
    In module 'AssetsLibrary' imported from /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/SYPictureMetadata/SYMetadata.m:14:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk/System/Library/Frameworks/AssetsLibrary.framework/Headers/ALAssetRepresentation.h:56:1: note: 'metadata' has been explicitly marked deprecated here
    - (NSDictionary *)metadata AL_DEPRECATED(4, "Use CGImageSourceCopyPropertiesAtIndex() to retrieve metadata from an image returned by the PHImageManager from the Photos framework instead");
    ^
    12 warnings generated.
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/CompressFileHandler.m:109:16: warning: unused variable 'swf' [-Wunused-variable]
        const char swf[3] = {'F', 'W', 'S'};
                   ^
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-1.1.1/ios/Classes/CompressFileHandler.m:110:16: warning: unused variable 'swc' [-Wunused-variable]
        const char swc[3] = {'C', 'W', 'S'};
                   ^
    2 warnings generated.
    2 warnings generated.
    /* com.apple.ibtool.document.warnings */
    /Users/bao-mac/Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_inappwebview-5.4.3+7/ios/Storyboards/WebView.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
    lib/src/pages/chat/chat_view.dart:148:51: Error: Required named parameter 'textEditingController' must be provided.
                              emojiView: ChatEmojiView(
                                                      ^
    ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_widget-2.3.0/lib/src/chat_emoji_view.dart:30:9: Context: Found this candidate, but the arguments don't match.
      const ChatEmojiView({
            ^^^^^^^^^^^^^
    lib/src/widgets/bottombar.dart:78:21: Error: No named parameter with the name 'steam'.
                        steam: item.steam,
                        ^^^^^
    ../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_openim_widget-2.3.0/lib/src/unread_count_view.dart:5:9: Context: Found this candidate, but the arguments don't match.
      const UnreadCountView({
            ^^^^^^^^^^^^^^^
    Failed to package /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'ZXingObjC' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'TOCropViewController' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'OrderedSet' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'MTBBarcodeScanner' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'ATBarSDK' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'JPush' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'JCore' from project 'Pods')
    /Users/bao-mac/Downloads/Open-IM-Flutter-Demo-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Bugly' from project 'Pods')

    Result bundle written to path:
    	/var/folders/0j/vs2dth5157q6r3s5lcf9wfn00000gn/T/flutter_tools.k17Gnr/flutter_ios_build_temp_dirQJKD4A/temporary_xcresult_bundle

Could not build the precompiled application for the device.

**Comment by lucasjinreal** [comment]
这垃圾库 感觉做出来就是骗钱的，没卵用

**Comment by std-s** [comment]
@simanlx  更新下代码。这个 widget 使用 flutter_openim_widget: 2.1.0
