### ISSUE TITLE
Getting errors while sending images and voice messages on Android

### ISSUE THREAD

**Issue by simanlx** [openimsdk/openim-flutter-demo#65]
E/GoLog   (18246): 2022-10-05 17:44:16.087 [ERRO] [PID:18246] [FilePath:open_im_sdk_conversation_msg.go:539] [OperationID:1664991856005] [checkErr  operationID[1664991856005], info[==> open_im_sdk/internal/obj_storage.(*Minio).upload()@89: : Get "http://127.0.0.1:10005/openim/?location=": dial tcp 127.0.0.1:10005: connect: connection refused]4565b74b3f8f1e2e90cf4e63091dc4dc ]
E/GoLog   (18246): 2022-10-05 17:44:16.087 [INFO] [PID:18246] [FilePath:conversation_msg.go:1495] [OperationID:internal] [doListener work.. 007]
E/GoLog   (18246): 2022-10-05 17:44:16.087 [INFO] [PID:18246] [FilePath:conversation_msg.go:1511] [OperationID:internal] [doUpdateConversation start .. 007]
E/GoLog   (18246): 2022-10-05 17:44:16.089 [INFO] [PID:18246] [FilePath:conversation_msg.go:1299] [OperationID:this is old conversation] [{single_1112705847 1 1112705847  123123 ic_avatar_02 0 0 0 {"clientMsgID":"4565b74b3f8f1e2e90cf4e63091dc4dc","createTime":1664991855970,"sendTime":1664991855970,"sessionType":1,"sendID":"2924134053","recvID":"1112705847","msgFrom":100,"contentType":102,"platformID":2,"senderNickname":"222","senderFaceUrl":"ic_avatar_06","content":"{\"sourcePath\":\"/storage/emulated/0/Pictures/1664866931288.jpg\",\"sourcePicture\":{\"type\":\"image/jpeg\",\"size\":5301,\"width\":110,\"height\":195},\"bigPicture\":{\"size\":0,\"width\":0,\"height\":0},\"snapshotPicture\":{\"size\":0,\"width\":0,\"height\":0}}","seq":0,"isRead":false,"status":1,"offlinePush":{},"pictureElem":{"sourcePath":"/storage/emulated/0/Pictures/1664866931288.jpg","sourcePicture":{"type":"image/jpeg","size":5301,"width":110,"height":195},"bigPicture":{"size":0,"width":0,"height":0},"snapshotPicture":{"size":0,"width":0,"height":0
E/GoLog   (18246): }},"soundElem":{"dataSize":0,"duration":0},"videoElem":{"videoSize":0,"duration":0,"snapshotSize":0,"snapshotWidth":0,"snapshotHeight":0},"fileElem":{"fileSize":0},"mergeElem":{},"atElem":{"isAtSelf":false},"faceElem":{"index":0},"locationElem":{"longitude":0,"latitude":0},"customElem":{},"quoteElem":{},"notificationElem":{},"messageEntityElem":{},"attachedInfoElem":{"groupHasReadInfo":{"hasReadCount":0,"groupMemberCount":0},"isPrivateChat":false,"hasReadTime":0,"notSenderNotificationPush":false,"isEncryption":false,"inEncryptStatus":false}} 1664991855970  0 false false false 1664991538273  }]
I/F-OpenIMSDK(native call flutter)(18246): { method:conversationListener,  type:onConversationChanged }
E/GoLog   (18246): 2022-10-05 17:44:16.097 [INFO] [PID:18246] [FilePath:conversation_msg.go:1513] [OperationID:internal] [doUpdateConversation end.. 007]
I/flutter (18246): Keyboard visibility direct query: false
I/flutter (18246): Keyboard visibility direct query: false
I/flutter (18246): Keyboard visibility direct query: false
I/flutter (18246): Keyboard visibility direct query: false
D/EGL_emulation(18246): app_time_stats: avg=54.26ms min=9.27ms max=281.35ms count=20
I/flutter (18246): send failed e :PlatformException(301, operationID[1664991856005], info[==> open_im_sdk/internal/obj_storage.(*Minio).upload()@89: : Get "http://127.0.0.1:10005/openim/?location=": dial tcp 127.0.0.1:10005: connect: connection refused]4565b74b3f8f1e2e90cf4e63091dc4dc , null, null)
I/flutter (18246): visible:0 true
I/flutter (18246): visible:1 true

**Comment by std-s** [comment]
@simanlx  服务器的配置调整下，config.yaml
