### ISSUE TITLE
Encountering an error 'Open_im_sdkSetOneConversationBurnDuration' when running 'flutter run' on macOS

### ISSUE THREAD

**Issue by g-mars** [openimsdk/openim-flutter-demo#68]
在MacOS终端，执行flutter pub get 后，再执行flutter run ，不能在模拟器正常运行起来。报错“Open_im_sdkSetOneConversationBurnDuration” 查找不到对应类。
<img width="905" alt="WechatIMG171" src="https://user-images.githubusercontent.com/12738410/204735032-fdcca78a-8aa6-456c-9608-c71c96cffc78.png">
<img width="1680" alt="WechatIMG172" src="https://user-images.githubusercontent.com/12738410/204735133-021cb570-1f81-4e32-84fe-46b3bf517e20.png">

**Comment by RanZiXuan** [comment]
解决完这个你就会发现下一个错 折磨你

**Comment by hrxiang** [comment]
> 解决完这个你就会发现下一个错 折磨你
目前flutter最新版本是[2.3.5+1](https://pub.flutter-io.cn/packages/flutter_openim_sdk)
pod update 将core包更新到最新的版本

**Comment by simanlx** [comment]
2.3.5+2 的 core 代码地址?  无语了 找不到了

**Comment by std-s** [comment]
https://github.com/openimsdk/openim-sdk-core/tree/test-v2.3.0release

**Comment by simanlx** [comment]
是2.3.5-b2
