### ISSUE TITLE
module 'app_installer' not found

### ISSUE THREAD

**Issue by SylviaRu** [openimsdk/openim-flutter-demo#69]
demo运行时报错 module 'app_installer' not found

**Comment by SylviaRu** [comment]
@hrxiang 辛苦能帮忙看下么

**Comment by hrxiang** [comment]
> @hrxiang 辛苦能帮忙看下么

看看 插件app_installer的版本 跟flutter 版本 ，去pub上搜索app_installer的最新版本然后替换试试

**Comment by SylviaRu** [comment]
@hrxiang 检查了，版本没问题，模拟器运行报这个错，真机运行没问题～
