### ISSUE TITLE
Unable to log out, getting an error when attempting to do so

### ISSUE THREAD

**Issue by DoraemonQiu** [openimsdk/openim-flutter-demo#75]
调用OpenIM.iMManager.logout()方法，无法退出登录，控制台输出内容：[ERRO] [PID:3181] [FilePath:ws.go:68] [OperationID:1681287190874] [ws ch recvMsg err, timeout]；抛出的异常：PlatformException(100, recv timeout, conn same, null, null)

**Comment by CatEatFishs** [comment]
我也遇到相同问题了
`
    Future logout() {
    return OpenIM.iMManager.logout().then((value) {
      userInfo = null;
    });
  }
`
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/24956075/233830162-cabd5c53-528e-44f4-a646-f58709b2fbe7.png">

**Comment by DoraemonQiu** [comment]
我这个问题后来发现是由于前端和后端用的SDK版本不同导致的，可以检查哈对应版本
