### ISSUE TITLE
Offline login issue, no need to connect to the server for verification?

### ISSUE THREAD

**Issue by laofu360** [openimsdk/openim-flutter-demo#78]
windows，下载demo后，按照文档搭建服务端和客户端。发现服务器离线情况下，客户端依然可以登录，并进入到聊天主界面，查看聊天，推测是用到本地缓存，但在android studio的控制台输出却看到 E/GoLog信息，看起来是在和服务器交互，但我本地服务器已经关掉，并且关闭本地网络连接！而且输出的go文件定位行数，跟我本机文件不符。比较费解，新手求解，谢谢！
![a](https://user-images.githubusercontent.com/67812647/236374495-42402ac1-9254-4446-bc8b-7493c0d1b358.png)

**Comment by laofu360** [comment]
搞错，这个是客户端本地的消息

**Comment by std-s** [comment]
确认链接的是你搭建的服务器？
