### ISSUE TITLE
Application does not receive offline messages through the long connection when in the background, how to handle it?

### ISSUE THREAD

**Issue by shenshenwlb** [openimsdk/openim-flutter-demo#79]
应用在后台，socket的数据接收方法收不到消息
  void recvNewMessage(Message msg) {
    initLogic.showNotification(msg);
    onRecvNewMessage?.call(msg);
  }

**Comment by std-s** [comment]
> 应用在后台，socket的数据接收方法收不到消息 void recvNewMessage(Message msg) { initLogic.showNotification(msg); onRecvNewMessage?.call(msg); }

离线消息使用PUSH方案。

**Comment by pokid** [comment]
> > 应用在后台，socket的数据接收方法收不到消息 void recvNewMessage(Message msg) { initLogic.showNotification(msg); onRecvNewMessage?.call(msg); }
> 
> 离线消息使用PUSH方案。

i got this problem too..i think its not offline,its just run in backound, and its not killed by system.  so why `onRecvOfflineNewMessage` cant receive message.
