### ISSUE TITLE
启动项目后发送不了消息

### ISSUE THREAD

**Issue by fs-sujieming** [openimsdk/openim-flutter-demo#8]
日志一直在报这个错
I/GoLog   ( 5342): [ init_login.go : 586 ] [ReadMessage message  1 <nil>]
I/GoLog   ( 5342): [ init_login.go : 606 ] [type failed, recv websocket.TextMessage  {"errCode":200,"errMsg":"invalid character 'ÿ' in literal false (expecting 'a')"}]

**Comment by hrxiang** [comment]
json解析错误。
