### ISSUE TITLE
It seems that not all the files have been included in the 3.0 version. The files under lib/src are all missing.

### ISSUE THREAD

**Issue by aliyoge** [openimsdk/openim-flutter-demo#82]
### What would you like to share?

<img width="218" alt="image" src="https://github.com/OpenIMSDK/Open-IM-Flutter-Demo/assets/12035097/87cebfc9-61e6-44b0-b983-3decda1932d2">

**Comment by hrxiang** [comment]
try again

**Comment by aliyoge** [comment]
> try again

@hrxiang 

Android的java文件也没传全😓
```bash
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cn.rentsoft.flutter.openim.consumer/cn.rentsoft.flutter.openim.consumer.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "cn.rentsoft.flutter.openim.consumer.MainActivity" on path: DexPathList[[zip file "/data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/lib/arm64, /data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/lib64/module/multimedia, /system/product/lib64]]
```

**Comment by hrxiang** [comment]
> > try again
> 
> @hrxiang
> 
> Android的java文件也没传全😓
> 
> ```shell
> java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cn.rentsoft.flutter.openim.consumer/cn.rentsoft.flutter.openim.consumer.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "cn.rentsoft.flutter.openim.consumer.MainActivity" on path: DexPathList[[zip file "/data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/lib/arm64, /data/app/~~RC3SNzIgYkR3QBuNraGd4w==/cn.rentsoft.flutter.openim.consumer-zsj3Yem5BnLAcTo9sLEHpQ==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/lib64/module/multimedia, /system/product/lib64]]
> ```

try again

**Comment by aliyoge** [comment]
iOS也报错 @hrxiang 

```bash
Swift Compiler Error (Xcode): Type 'AdvancedMsgListener' does not conform to protocol 'Open_im_sdk_callbackOnAdvancedMsgListenerProtocol'
/Users/xxxxxx/.pub-cache/git/Open-IM-SDK-Flutter-bd364ea2fddabcfa25e58d83125f7bc3070ef5d2/ios/Classes/Module/MessageManager.swift:282:13

Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited
```

**Comment by hrxiang** [comment]
pod cache clean OpenIMSDKCore --all

pod update

**Comment by aliyoge** [comment]
> pod cache clean OpenIMSDKCore --all
> 
> pod update

清了也没用

```bash
$  pod cache clean OpenIMSDKCore --all

[!] No cache for pod named OpenIMSDKCore found
```
还是报一样的错

**Comment by aliyoge** [comment]
手动删除flutter pub的git缓存，删掉pubspec.lock重新 pub get后的版本就对了。
建议仓库的pubspec.lock也固定一下。
