### ISSUE TITLE
In the 3.0 version, features like sending voice messages, sending emojis, sharing location, and sending files are still missing.

### ISSUE THREAD

**Issue by aliyoge** [openimsdk/openim-flutter-demo#83]
### What would you like to share?

<img width="377" alt="image" src="https://github.com/OpenIMSDK/Open-IM-Flutter-Demo/assets/12035097/09c6cc1f-323a-41f0-b240-98fb31a68e84">

**Comment by hrxiang** [comment]
https://www.pgyer.com/openim_flutter_c_base_open

**Comment by aliyoge** [comment]
@hrxiang demo里面不提供这些功能吗？
