### ISSUE TITLE
Bug:  Failed to build iOS app

### ISSUE THREAD

**Issue by yuantianxiang** [openimsdk/openim-flutter-demo#86]
### What happened?

Error (Xcode): ../../../.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-11.0.1/lib/src/extended_render_editable.dart:82:40: Error: Type 'BidirectionalIterator' not found.

Could not build the application for the simulator.

### What did you expect to happen?

成功运行

### How can we reproduce it (as minimally and precisely as possible)?

运行不起来。

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Hello, these are the version issues of the three-party package, please update the latest code, the version of the package has been fixed.
Use real machine compilation.

**Comment by std-s** [comment]
There has been no response for a long time, so I will close this question first.
