### ISSUE TITLE
Bug: <describe the error>

### ISSUE THREAD

**Issue by Rn17310118925** [openimsdk/openim-flutter-demo#88]
### What happened?

 PlatformException(10005, error *errors.withStack not implement CodeError: ==> open_im_sdk/pkg/db.(*DataBase).GetConversationListSplitDB()@91: GetFriendList failed: sql: database is closed, null, null)

### What did you expect to happen?

Android 回话列表收取不到

### How can we reproduce it (as minimally and precisely as possible)?

消息获取不到

### version

sdk 3.2.0

### Cloud provider

minno

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Are there more logs?

**Comment by std-s** [comment]
No response for too long, close it temporarily.
