### ISSUE TITLE
May I know when flutter_openim_sdk will be upgraded to the latest version 3.2 or above, and when it will support the latest Flutter version 3.13 or above?

### ISSUE THREAD

**Issue by fuxianwei** [openimsdk/openim-flutter-demo#89]
### What happened?

目前升级最新版本flutter_openim_sdk项目报错，请问下什么时候兼容最新flutter_openim_sdk 3.2.0 版本了

### What did you expect to happen?

升级flutter_openim_sdk 3.2.0出现兼容问题

### How can we reproduce it (as minimally and precisely as possible)?

升级flutter_openim_sdk 3.2.0

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by std-s** [comment]
Will be upgraded as soon as possible.

**Comment by std-s** [comment]
No response for too long, close it temporarily.
