### ISSUE TITLE
Bug: Error: Required named parameter 'devicePixelRatio' must be provided.

### ISSUE THREAD

**Issue by lakerchen** [openimsdk/openim-flutter-demo#91]
### What happened?

Got errors when I execute the commad `flutter run`

```
% flutter run                                                  
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...                                              4.9s
Running Xcode build...                                                  
Xcode build done.                                           46.0s
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/extended_image-7.0.2/lib/src/gesture/page_view/gesture_page_view.dart:21:49: Error: Required named parameter
'devicePixelRatio' must be provided.


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

### What did you expect to happen?

Launch the demo app successfully in the iPhone simulator

### How can we reproduce it (as minimally and precisely as possible)?

Execute the commad `flutter run` in macOS

### version

Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (5 days ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0

### Cloud provider

None

### OS version

Apple M1 Pro
macOS 13.5

**Comment by std-s** [comment]
hi, 
the current demo is developed based on Flutter SDK version 3.7.12. If you use other versions, please adjust it yourself.

**Comment by lakerchen** [comment]
I have adjusted Flutter SDK to 3.7.12

```
(base) lakerchen@lakerchen-PC Open-IM-Flutter-Demo % flutter --version
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (5 months ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1
```

And it still doesn't work

```
(base) lakerchen@lakerchen-PC Open-IM-Flutter-Demo % flutter run
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...                                              4.3s
Running Xcode build...                                                  
Xcode build done.                                           48.1s
Failed to build iOS app
Error (Xcode): lib/core/im_callback.dart:222:28: Error: Type 'SignalingInfo' not found.


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

**Comment by std-s** [comment]
@lakerchen hi,
Please get the latest Demo code.

**Comment by lakerchen** [comment]
I pull the latest code in main branch, and still got error.

<img width="465" alt="image" src="https://github.com/openimsdk/open-im-flutter-demo/assets/3245703/4ff45438-4dca-4b11-9d43-20133b1876f3">

**Comment by std-s** [comment]
hi，The version of the SDK uses 3.3.0, do not change it.

**Comment by std-s** [comment]
No response for too long, close it temporarily.
