### ISSUE TITLE
🤖Failing-test: The SDK connection status for a long time is connecting or failed.

### ISSUE THREAD

**Issue by 4815180** [openimsdk/openim-flutter-demo#93]
### Which test are failing?

登录demo后，SDK状态为可能会维持接近1分钟的连接中或反复连接失败

### Since when has it been failing?

demo测试第一次

**Comment by std-s** [comment]
@4815180  Hi, please upload the logs from "Initializing SDK" to the end of synchronization here. Let's follow up.

**Comment by 4815180** [comment]
[Flutter Logs.txt](https://github.com/openimsdk/open-im-flutter-demo/files/13314501/Flutter.Logs.txt)

**Comment by std-s** [comment]
@4815180 hi,
Are you sure you want to use the port?

 "apiAddr":"http://new.618w.cn:10002","wsAddr":"ws://new.618w.cn:10001"

**Comment by 4815180** [comment]
> @4815180 hi, Are you sure you want to use the port?
> 
> "apiAddr":"[http://new.618w.cn:10002","wsAddr":"ws://new.618w.cn:10001](http://new.618w.cn:10002%22,%22wsAddr%22:%22ws://new.618w.cn:10001)"

Due to my lack of registration in mainland China, I am unable to use HTTPS. In order to avoid changing my IP address in the future, I have adopted this approach. However, it has resulted in an exception. When I switch to http://ip:10001 and http://ip:10002, the issue is resolved. I am quite confused.

**Comment by std-s** [comment]
hi, You can make the following changes.  

http://ip:10001/ => http://host/msg_gateway
http://ip:10002/ => http://host/api

**Comment by std-s** [comment]
After no response for a long time, I closed it first.
