### ISSUE TITLE
ios packaging shows that flutter_openim_sdk cannot be found

### ISSUE THREAD

**Issue by charlesdev23** [openimsdk/openim-flutter-demo#94]
### What happened?

flutter run 在xcode打包报错 
<img width="610" alt="image" src="https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/edf9ba72-f9cc-4eba-8a47-f6d0782aaba4">
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/837c3906-6cba-4fa2-adec-163a5344a144)
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/cc8069d0-2360-4d6c-8802-b23e94db6af1)
在pub.dev目录下能找到包
![image](https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/4ed775a7-e80a-4e0e-a926-acf01603a53c)
<img width="237" alt="image" src="https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/2cc04ee0-d4ba-463b-b338-35f2684021a9">

iOS打包版本：
<img width="527" alt="image" src="https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/19794aa8-3724-4fe3-b246-d68a39e4c38c">
<img width="636" alt="image" src="https://github.com/openimsdk/open-im-flutter-demo/assets/150661050/1b30b319-b119-448c-8e6f-fd46c969366b">

### What did you expect to happen?

---

### How can we reproduce it (as minimally and precisely as possible)?

---

### version

13.0

### Cloud provider

----

**Comment by std-s** [comment]
@charlesdev23 hi,
1. Flutter uses version 3.7.12;
2. If you want to run iOS, please use a real machine.

**Comment by charlesdev23** [comment]
Could you tell me why it can not run in simulator?  @std-s

**Comment by lucasjinreal** [comment]
Why have to using real device? Uses using latest flutter like 3.16 can not run?

flutter 3.16 introduce a new renderer in Android, which brings much more smooth experiences to app, please consider upgrade to latest flutter

**Comment by std-s** [comment]
hi, Will do this this week.

**Comment by std-s** [comment]
After no response for a long time, I closed it first.
