### ISSUE TITLE
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### ISSUE THREAD

**Issue by lucasjinreal** [openimsdk/openim-flutter-demo#97]
### What happened?

Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### What did you expect to happen?

Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### How can we reproduce it (as minimally and precisely as possible)?

Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### Anything else we need to know?

Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### version

<details>
```console
$ {name} version
# paste output here
```
</details>
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### Cloud provider

<details>
</details>
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>
Parse Issue (Xcode): Module 'flutter_openim_sdk' not found

**Comment by std-s** [comment]
hi, Please follow the steps below. And make sure you are using flutter3.7.12 version.

flutter clean
flutter pub get
cd ios
pod install
rm -f Podfile.lock
rm -rf Pods
Run Archive after connecting to the real device

**Comment by std-s** [comment]
No response for a long time, please close this question first.
